---
classoption: "runningheads"
title: "Flujos de información, adaptación y emergencia en sistemas circulares de suministros\\thanks{Lydia Bals, Wendy L. Tate, Lisa M. Ellram}"
shorttitle: "Cadenas de Suministros en Economía Circular"
# If the paper title is too long for the 
# running head, you can set an abbreviated 
# paper title here.
# shorttitle: "Abbreviated paper title"
authors: 
  - name: "Ian Johnson"
    inst: "1"
    orcid: "0009-0001-2786-9385"
  - name: "Carolina Fernández"
    inst: "1"
    orcid: "0009--0004-4219-1041"
  - name: "Julián Hidalgo"
    inst: "1"
    orcid: "0009-0002-0617-6800"

# First names are abbreviated in the running head.
# If there are more than two authors, 'et al.' is used.
authorrunning: "Grupo Los Ignorantes" 
institutes: 
   - name: "Grupo Los Ignorantes"
    # email: "lncs@springer.com"
    # url: "http://www.springer.com/gp/computer-science/lncs"

abstract: | 
  Este documento resume el capítulo 3 del libro “Circular Economy Supply Chains”. El capítulo estudia el concepto de “sistema circular de suministros” y la forma en que los flujos de información entre sus agentes facilita su crecimiento. Finalmente se analizan los resultados del flujo de información, que se resumen en nuevos agentes y nuevos patrones espacio-temporales.
keywords: 
  - Economía circular
  - Cadena de suministros circular
  - Red de suministros
  - Sistemas adaptativos complejos
  - Flujos de información
  - Emergencia
bibliography: lncs-test.bib
# Use csl when using default citation_package for Pandoc citeproc
csl: https://www.zotero.org/styles/springer-lecture-notes-in-computer-science
# citations with arabic numbers is prefered when using natbib
natbiboptions: numbers

output: 
  rticles::lncs_article:
    citation_package: default # or natbib
  pdf_document:
    css: styles.css
    background-color: "#FFFFF0"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")  # This forces knitr to label all figures.
```

# Introducción

Se introduce la economía circular mediante una analogía con la cadena de suministros de la industria papelera en 1820, en la cual la escasez de fibras hacía que las empresas dependieran de los restos de prendas que sus compradores pudieran aportar. En este sentido, la economía circular se define como \textbf{la forma de recircular materiales mediante técnicas como reutilización, rediseño y reciclaje.}\

Sin embargo, la razón para impulsar la economía circular en el contexto moderno ya no es la escasez, sino la forma en que el \textbf{exceso de consumo} genera pérdidas económicas y daños al medioambiente a través del aumento de flujos de desechos o la sobreexplotación de recursos naturales.\

Se entiende que el motivo para avanzar hacia una economía circular es la respuesta a estas señales, y se explica que las empresas modernas no tienen control total sobre la cadena de suministros, sino que dependen de que otros actores quieran involucrarse en la economía circular. Este capítulo intenta explicar el modo en que las señales de información pueden fomentar el desarrollo de la economía circular.

# Aparición de nuevos modelos de sistema

Se define al \textbf{sistema de suministros} como el sistema que incluye todos los actores relevantes en la producción (principalmente actores externos), mientras que la cadena directa de productores de bienes se define como \textbf{red de suministros}

## Cadenas de suministros como SAC.

Un SAC (sistema adaptativo complejo) es \textbf{un sistema que contiene una gran cantidad de agentes que interactúan, se adaptan y aprenden}. En este tipo de sistemas los agentes no se relacionan linealmente, sino que siguen determinados patrones de comportamiento. Estos son tácitos y surgen debido a la interacción independiente entre agentes (sin intervención de una autoridad central), en lo que se conoce como el \textbf{mecanismo de auto-organización.}\

Un sistema de suministros se considera como un SAC debido a las relaciones no lineales entre sus agentes. Los comportamientos clásicos de un SAC incluyen la capacidad de respuesta de los agentes, la interconexión y la evolución conjunta con el entorno. En una red de suministros, los agentes no se conectan con toda la red ni tienen influencia absoluta sobre ella, sino que toman información de sus compradores y suministradores locales para tomar decisiones. La red de suministros también es afectada por factores externos.

## Información necesaria para la adaptación de cadenas de suministro.

La adaptación surge a partir de acciones condicionales en respuesta a flujos de información. En un SAC, un agente A toma una decisión y otro agente B responde mediante una decisión condicional en base a la información recibida. Al acumular las decisiones de todos los agentes se construye una estructura dinámica que cambia junto con los comportamientos de los agentes de la red y el entorno. Los flujos de información deben ser transmitidos en tiempo y forma para evitar acciones erróneas o subóptimas por parte del agente B.\

El flujo de información crea una dependencia entre ambos actores, ya que B busca su punto óptimo de funcionamiento para la información que le brindan A y el entorno, a la vez que busca comprender el patrón de comportamiento que siguen sus de decisión.\

Algunas definiciones le dan al flujo de información una trascendencia similar a los flujos de dinero o bienes materiales, ya que, incluso si los flujos de información fueran incompletos o deficientes, las empresas se ven obligadas a basar sus decisiones en ellos. Un flujo ideal de información ayuda al éxito de la cadena de suministros, ya que contiene datos actualizados y precisos. Por lo tanto, se dice que las empresas mejoran su esquema de decisión en base a la calidad de la información recibida.

## Desde la adaptación a la emergencia

Como ningún agente tiene control sobre todos los demás agentes de una red, los patrones de comportamiento de la red surgen a partir del modo en que agentes individuales se adaptan a sus flujos de información locales. Así, toda la estructura de la cadena de producción se construye a partir de la capacidad de respuesta de cada agente del sistema.\

Además de tener capacidad de respuesta, los agentes de una red de suministros deben controlar aquellos aspectos que estén a su alcance para evitar desbalances en el resto de la cadena productiva.

# Flujos de información para la producción circular

Estas dinámicas CAS pueden ayudarnos a entender los tipos de información necesaria para que surjan sistemas circulares de suministro. Específicamente, los actores necesitan información de (1) redes locales de suministro, (2) sistemas extendidos de suministro, e idealmente también (3) la biósfera, de acuerdo con la definición de economía circular de Murray “maximizar el funcionamiento del ecosistema”. Necesitan continuamente tales flujos de información y capacidad adaptativa para reaccionar, ya que no hay equilibrio único en ningún CAS. Los sistemas están continuamente evolucionando, significando que los actores necesitan aprender y adaptarse a las condiciones cambiantes a medida que vienen (Gunderson & Holling, 2002). Por lo tanto, necesitamos información continuamente para adaptarnos.

## Redes de suministros locales

Las redes locales circulares de suministro reducen el consumo de energía necesario para transporte y hacen más fácil monitorear los impactos sistémicos, por lo que son prioritarias en regiones geográficas limitadas (Korhonen, 2020).
Dos tipos clave de información local son necesarios: que materiales de desecho están disponibles, y que puede hacerse con ellos. Estos flujos de información toman dos roles descritos por Tate et al. (2019) como carroñeros y descomponedores. Los carroñeros son “compañías que se alimentan de recursos de desecho de otras compañías en el sistema, redistribuyendo recursos de regreso al sistema que las compañías pueden reutilizar”. Los descomponedores, por otro lado, son “compañías que usan recursos de desecho de los productores, consumidores y carroñeros”.
Una fuente de materiales de desecho para carroñeros son los fabricantes locales, que pueden tener desechos de flujo lateral que otras firmas podrían usar (Wells & Seitz, 2005). Se necesitan flujos de información para entender qué materiales están disponibles, así como las cantidades y ritmos con que los residuos son producidos. Las cantidades limitadas pueden afectar la  capacidad de las empresas para escalar la producción circular (Patala, Albareda & Halme, 2018; Sprecher et al., 2017).
Sin embargo, las compañías tradicionalmente no comparten información sobre sus corrientes de desechos, por miedo a revelar información sensible (Patala et al., 2018). La proximidad geográfica cercana puede facilitar la colaboración (Prendeville, Cherim & Bocken, 2018) e incluso aliviar potencialmente problemas de confianza (Patala e al., 2018). Los sistemas de simbiosis industrial, que son típicamente conjuntos de empresas delimitadas geográficamente que ingresan los desechos de otros como materia prima para sus propios procesos (Chertow, 2000), pueden facilitar una confianza más fuerte, integración, e información compartida entre firmas (Lopes de Sousa Jabbour et al., 2019).
La cuestión de la disponibilidad y previsión de los residuos es incluso más difícil para compañías usando desechos postconsumo, ya que hay poca información sobre estos en específico. Sin datos sobre cantidades de desechos disponibles, las empresas podrían terminar teniendo muy poco o demasiado del material que necesitan.
Los carroñeros en un sistema de suministro circular pueden también ayudar a superar una de las barreras claves para cambiar hacia la circularidad: la logística inversa para llevar los materiales de desecho a un lugar centralizado para el procesamiento (Farooque et al., 2019). El cambio a los sistemas circulares de suministro está abriendo nuevos caminos para que otras firmas comiencen a  asumir este rol a través de nuevos modelos comerciales de reciclaje (Lüdeke-Freund, Gold & Bocken, 2019; Patala et al., 2018). Un ejemplo son los sistemas de recolección de residuos geográficamente descentralizados, como los programas de devolución de botellas en el punto de venta que usan escáneres y datos de productos (Miller, 2018).
En lugares donde no existe una infraestructura de gestión de residuos bien desarrollada, el papel de recolector también puede ser desempeñado por individuos que venden los residuos recolectados a instalaciones centralizadas (Troschinetz y Mihelcic, 2009).
Para utilizar los materiales recolectados, los descomponedores primero necesitan información sobre su composición. En el caso de la remanufacturación, también necesitan información sobre la vida útil del producto para ayudar a evaluar su estado (Laubscher y Marinelli, 2014). Los productores pueden ayudar a los recolectores y descomponedores poniendo a su disposición información sobre el producto, lo que hace que la recolección, clasificación y producción secundaria sean más factibles (Jabbour, Jabbour, Sarkis y Filho, 2017; Laubscher y Marinelli, 2014). Nuevas tecnologías como la identificación por radiofrecuencia (RFID) y el blockchain son prometedoras para permitir ideas como los pasaportes de materiales (Garcia-Torres, Albareda, Rey-Garcia y Seuring, 2019; Tate et al., 2019).
También se necesita información sobre lo que pueden hacer con los materiales residuales. Aunque las prácticas modernas de reciclaje para algunos materiales existen desde hace décadas, los científicos de materiales todavía están estudiando cómo dar una nueva vida a otros materiales y como pueden desarrollar nuevas alternativas de materiales que sean más propicias para la circularidad.

## Sistemas de suministros extendidos

Un flujo crítico es la información de los gobiernos a las redes de suministro sobre sus iniciativas circulares. Los gobiernos pueden desempeñar un papel importante incentivando la aparición de redes de suministro circular a través de políticas amigables con la circularidad, financiamiento, investigación, desarrollo de asociaciones y/o estándares de adquisición pública (de Jesus & Mendonça, 2018; Masi, Day, & Godsell, 2017; Patala et al., 2018; Prendeville et al., 2018; Winans et al., 2017). Podrían ir aún más lejos al facilitar proactivamente la economía circular a través de estándares de productos, como la facilidad de desmontaje (Vanegas et al., 2017), o mediante el lanzamiento de experimentos circulares a nivel de la ciudad (Prendeville et al., 2018). Las regulaciones sobre residuos y lo que se puede hacer con ellos, y la retirada del financiamiento previamente ofrecido, pueden ser barreras para la aparición de redes de suministro circular (de Jesus & Mendonça, 2018; Winans et al., 2017).
Otro flujo relevante es sobre las proyecciones de escasez de materiales críticos, lo que podría ser un impulsor hacia la circularidad. Pueden ser impulsadas por la disminución de las cantidades que se pueden extraer o por interrupciones temporales en las cadenas de suministro (Gaustad, Krystofik, Bustamante y Badami, 2018).
Por último, los minoristas que buscan adoptar la economía circular también necesitan comprender la disposición de los consumidores a comprar sus productos circulares o traer su propio desperdicio para ser reutilizado. Uno de los problemas clave es la percepción de que los productos hechos de materiales de desperdicio son de menor calidad, lo que puede impedir que los bienes circulares desplacen a los no circulares. Prometedoramente, parece que la demanda de productos circulares ha estado mejorando, lo que podría mitigar el riesgo de este tipo de "rebote de la economía circular" (Zink & Geyer, 2017).
En algunos sistemas circulares, los consumidores también pueden ser la fuente de materiales de desecho para los recolectores. Los consumidores necesitan comprender dónde encontrar a los recolectores, o cómo convertirse ellos mismos en recolectores así como cualquier requisito de material: por ejemplo si necesitan ser limpiados o desmontados antes de llevarlos a un recolector. Además, lograr que los consumidores se sumen a iniciativas circulares podría potencialmente crear un entorno político más favorable, al menos en sistemas democráticos.

## Impactos en la biósfera

Finalmente, los sistemas de suministro circular deben tener flujos de información que les permitan comprender y adaptarse a los impactos de la humanidad en la biósfera. Las empresas necesitan cambiar a una nueva lógica que centre la sostenibilidad ecológica a largo plazo en la toma de decisiones (Montabon, Pagell y Wu, 2016). Necesitan flujos de información sobre indicadores biofísicos a múltiples escalas y la capacidad de tomar decisiones basadas en ellos. Se incorporan los indicadores de los límites planetarios en las evaluaciones del ciclo de vida o en nuevas herramientas "para facilitar la evaluación predictiva" (Clift et al., 2017, p. 4).
Los actores necesitan comprender cómo trabajar dentro de cantidades y tasas de extracción y descarte de recursos, apropiadas para la biosfera. Esto es importante para la gestión tanto de recursos biológicos como tecnológicos, ya que los primeros "perturbarán seriamente nuestros ecosistemas" si no se liberan "cuidadosamente, a un ritmo en resonancia con el orden natural" (Skene, 2018, p. 485). 
Se debe contar con organizaciones en los sistemas de suministro circular más amplios que puedan rastrear y operacionalizar información a diferentes escalas. Los actores gubernamentales que monitorean estas escalas pueden incorporar datos en incentivos y políticas, y las organizaciones que monitorean cambios locales y más rápidos también pueden informar sobre los impactos en el terreno.

# Posible emergencia en suministros circulares

El texto en un inicio habla sobre cómo pueden surgir nuevas estructuras y patrones en sistemas circulares de suministro si los actores eligen adaptarse a ellos. Se mencionan dos tipos de surgimiento en particular: nuevos roles y redes de actores, y nuevos patrones espaciales y temporales. Se explica cómo, a través de la recepción de señales de información específicas, pueden surgir nuevos roles y redes de producción circular y cómo estos se relacionan con las condiciones ambientales y gubernamentales. Se utiliza el  siguiente ejemplo para ilustrar esto: \

Para ilustrar esto, podemos volver al caso de la empresa textil Finlayson, que produce alfombras de trapo con las sábanas viejas de sus clientes: Las alfombras de trapo son una artesanía tradicional finlandesa que ha desaparecido en gran medida en los últimos años. Finlayson quería revivir esta tradición y al mismo tiempo abordar el problema de los residuos textiles en Europa. En la primavera de 2016, realizaron su primera campaña de recolección de sábanas viejas de los clientes y recibieron 11 toneladas de ellas. A cambio, los clientes recibieron descuentos en sus próximas compras para demostrar que "las sábanas viejas tienen valor". Debido a que la producción de alfombras de trapo había disminuido en popularidad, Finlayson no pudo encontrar una máquina para hacerlas, pero encontró un pequeño proveedor en Finlandia que ahora trabaja a tiempo completo gracias al contrato de Finlayson.\

En este ejemplo, la red de suministro para las alfombras de trapo surgió a través de la autoorganización. Finlayson difundió información sobre la recolección de sábanas y los incentivos a los clientes dentro de su sistema de suministro extendido. Los clientes que se adaptaron a esa información al llevar sus sábanas se convirtieron en parte de la red de suministro directa. En el lado de la fabricación, Finlayson encontró, a través de alguna señal de información, uno de los últimos productores industriales de alfombras de trapo en Finlandia. Gracias al contrato de Finlayson, surgieron nuevos patrones temporales (trabajando a tiempo completo) y estructuras de recursos (empleando más personal) dentro de ese proveedor. Toda la iniciativa de las alfombras de trapo fue impulsada por dos piezas de información del sistema de suministro extendido: (1) el problema de los residuos textiles en Europa y (2) la información implícita de que habría un mercado para revivir las tradicionales alfombras de trapo finlandesas.

## Nuevos patrones espaciales y temporales

En esta parte, se habla sobre cómo en los sistemas de suministro circular pueden surgir nuevos patrones y estructuras si los actores se adaptan a la información que reciben. Se pueden dar dos tipos de surgimiento: nuevos roles y redes de actores, y nuevos patrones espaciales y temporales. En cuanto a los patrones espaciales, pueden surgir sistemas de suministro locales debido a la capacidad de los actores de monitorear y confiar entre sí. Además, la producción circular local puede ayudar a construir una mayor resiliencia a las escasez de materiales críticos. En cuanto a los patrones temporales, los sistemas de suministro circular pueden extender los horizontes de tiempo en los que la información del producto y del material puede viajar. Las tecnologías como blockchain pueden actuar como un puente hacia el futuro, fomentando que los actores del presente piensen en cómo hablar con los sistemas de suministro circular en ese tiempo lejano.\

La ayuda de los socios que monitorean diversas escalas también puede extender los horizontes espaciales y temporales considerados. Los actores podrían ser más propensos a tener en cuenta los impactos distantes en la biosfera y las escaseces críticas de materiales si esa información es monitoreada y escalada hacia indicadores útiles para la toma de decisiones a nivel de la empresa. Además, podrían tener la información necesaria para sincronizar mejor sus flujos de materiales con los ciclos regenerativos y/o absorbentes de la biosfera.

## La información por sí sola no es suficiente

En este apartado, en resumen, aunque los flujos de información son necesarios para la aparición de redes y sistemas circulares de suministro, no son suficientes por sí solos. Los actores necesitan tener los recursos físicos y las capacidades para adaptarse a esa información, lo que incluye máquinas de producción, sistemas de tecnología de la información, vehículos de transporte y personal con las habilidades para utilizar esos recursos. Además, se necesitan recursos financieros para financiar todo ello. Es importante tener la voluntad de adaptarse constructivamente a las señales de información recibidas, lo que puede requerir nuevas lógicas e incentivos institucionales.

# Conclusión

En este capítulo se buscó conceptualizar cómo la adaptación autónoma a las señales de información puede llevar a la aparición de sistemas circulares de suministro. La información sobre las redes de suministro locales, sistemas de suministro extendidos e impactos en la biosfera es particularmente importante para la producción circular. Se discutieron las limitaciones de esta teoría y se sugirieron direcciones para futuras investigaciones empíricas, como estudiar cómo las dinámicas sociales, políticas, institucionales y financieras impactan la capacidad adaptativa en los sistemas de suministro circular.

